title: Crescent Moonlight
author:
  name: princess201
  email: narelim0119@gmail.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
#theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima specific settings, which are only available from Minima 3.0 onward.
# minima:
  # skin: classic
  # nav_pages:
    # - test.md
    # - info.md
    # - notice.md

# Site settings
url: "https://narelim.github.io"
baseurl: ""
future: true

